# Generated by Django 6.0 on 2026-01-03 01:56

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
import phonenumber_field.modelfields
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "marketing_blocks",
                    wagtail.fields.StreamField(
                        [("marketing_block", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter the block title",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Enter the block content",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.blocks.ListBlock",
                                (2,),
                                {
                                    "help_text": "Select one or two images for column display. Select three or more images for carousel display."
                                },
                            ),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Select one image for background display.",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "vh-100 app-ribbon",
                                    "form_classname": "full title",
                                    "help_text": "Enter a CSS class for styling the marketing block",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "img-thumbnail p-5",
                                    "form_classname": "full title",
                                    "help_text": "Enter a CSS class for styling the column display image(s)",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "d-flex flex-row",
                                    "form_classname": "full title",
                                    "help_text": "Enter a CSS class for styling the layout.",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("content", 1),
                                        ("images", 3),
                                        ("image", 4),
                                        ("block_class", 5),
                                        ("image_class", 6),
                                        ("layout_class", 7),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "About Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CareersPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ClientsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clients Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("address", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True, verbose_name="Website")),
                (
                    "ein",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="EIN"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServicesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Services Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("address", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True, verbose_name="Website")),
                ("publish", models.BooleanField(default=False)),
                ("link", models.BooleanField(default=False)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="aclark@aclark.net",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=300, null=True)),
                ("last_name", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="E-Mail Address",
                    ),
                ),
                (
                    "mobile_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Mobile Phone",
                    ),
                ),
                (
                    "office_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Office Phone",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "fax",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="UUID")),
                ("number", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=300, null=True, verbose_name="URL"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("html", models.BooleanField(default=False, verbose_name="HTML")),
                ("text", models.TextField(blank=True, null=True)),
                ("contacts", models.ManyToManyField(blank=True, to="db.contact")),
                ("notes", models.ManyToManyField(blank=True, to="db.note")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="company",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="client",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("page_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Hourly Rate (United States Dollar - USD)",
                    ),
                ),
                (
                    "unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=1.0,
                        max_digits=12,
                        null=True,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, null=True, verbose_name="Avatar URL"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("job_title", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "twitter_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("slug", models.SlugField(blank=True, max_length=150, null=True)),
                (
                    "lounge_password",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "lounge_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("mail", models.BooleanField(default=False)),
                ("dark", models.BooleanField(default=True, verbose_name="Dark Mode")),
                (
                    "github_access_token",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("notes", models.ManyToManyField(blank=True, to="db.note")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Project Code"
                    ),
                ),
                ("total_hours", models.FloatField(blank=True, null=True)),
                ("billable_hours", models.FloatField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_spent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_remaining",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_costs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "team_costs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "expenses",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "po_number",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="PO Number"
                    ),
                ),
                ("draggable_positions", models.JSONField(blank=True, null=True)),
                (
                    "github_project",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="GitHub Project",
                    ),
                ),
                (
                    "github_repository",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="GitHub Repository",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db.client",
                    ),
                ),
                ("companies", models.ManyToManyField(to="db.company")),
                ("notes", models.ManyToManyField(blank=True, to="db.note")),
                (
                    "team",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("subject", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "issue_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Issue Date",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due"),
                ),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="PO Number"
                    ),
                ),
                (
                    "sa_number",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Subcontractor Agreement Number",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Invoice Amount",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("discount", models.IntegerField(blank=True, null=True)),
                ("ein", models.IntegerField(blank=True, null=True, verbose_name="EIN")),
                ("tax", models.IntegerField(blank=True, null=True)),
                ("tax2", models.IntegerField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default="United States Dollar - USD",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        blank=True, default="$", max_length=300, null=True
                    ),
                ),
                ("doc_type", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "gross",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=1.0,
                        max_digits=12,
                        null=True,
                        verbose_name="Hours",
                    ),
                ),
                ("reset", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db.company",
                    ),
                ),
                ("contacts", models.ManyToManyField(blank=True, to="db.contact")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("notes", models.ManyToManyField(blank=True, to="db.note")),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db.project",
                    ),
                ),
            ],
            options={
                "ordering": ["subject"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("notes", models.ManyToManyField(blank=True, to="db.note")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=1.0,
                        max_digits=12,
                        null=True,
                        verbose_name="Unit",
                    ),
                ),
                ("notes", models.ManyToManyField(blank=True, to="db.note")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("clients", models.ManyToManyField(blank=True, to="db.client")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db.company",
                    ),
                ),
                ("contacts", models.ManyToManyField(blank=True, to="db.contact")),
                ("invoices", models.ManyToManyField(blank=True, to="db.invoice")),
                ("notes", models.ManyToManyField(blank=True, to="db.note")),
                ("projects", models.ManyToManyField(blank=True, to="db.project")),
                ("reports", models.ManyToManyField(blank=True, to="db.report")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tasks", models.ManyToManyField(blank=True, to="db.task")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="project",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.task",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.task",
            ),
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "issue_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Issue Date",
                    ),
                ),
                ("notes", models.ManyToManyField(blank=True, to="db.note")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("invoiced", models.BooleanField(default=False)),
                (
                    "date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=1.0,
                        max_digits=12,
                        null=True,
                        verbose_name="Hours",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=1.0,
                        max_digits=12,
                        null=True,
                        verbose_name="Quantity",
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=1.0,
                        max_digits=12,
                        null=True,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=1.0,
                        max_digits=12,
                        null=True,
                        verbose_name="Total Price",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db.client",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="times",
                        to="db.invoice",
                    ),
                ),
                ("notes", models.ManyToManyField(blank=True, to="db.note")),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
