# Generated by Django 6.0 on 2026-02-01 21:00

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        help_text="Stripe Payment Intent ID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Checkout Session ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount in dollars",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd",
                        help_text="Payment currency (e.g., usd, eur)",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="Payment status (pending, succeeded, failed, canceled)",
                        max_length=50,
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Customer email from Stripe",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata from Stripe",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Invoice this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="db.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
