# Generated by Django 6.0 on 2026-01-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.IntegerField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="Invoice Number",
            ),
        ),
    ]
