# Generated by Django 6.0 on 2026-01-15 03:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        # Remove unused field from Client model
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
        # Remove unused field from Invoice model
        migrations.RemoveField(
            model_name="invoice",
            name="gross",
        ),
        # Remove unused fields from Project model
        migrations.RemoveField(
            model_name="project",
            name="total_hours",
        ),
        migrations.RemoveField(
            model_name="project",
            name="billable_hours",
        ),
        migrations.RemoveField(
            model_name="project",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="project",
            name="budget_spent",
        ),
        migrations.RemoveField(
            model_name="project",
            name="budget_remaining",
        ),
        migrations.RemoveField(
            model_name="project",
            name="total_costs",
        ),
        migrations.RemoveField(
            model_name="project",
            name="team_costs",
        ),
        migrations.RemoveField(
            model_name="project",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="project",
            name="expenses",
        ),
        migrations.RemoveField(
            model_name="project",
            name="companies",
        ),
    ]
