# Generated by Django 2.1.2 on 2018-10-20 12:47

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0003_auto_20181020_1246")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dashboard_items",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("tools", "Tools"), ("times", "Times"), ("totals", "Totals")],
                max_length=18,
                null=True,
                verbose_name="Dashboard Items",
            ),
        )
    ]
