# Generated by Django 2.1.2 on 2018-10-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0004_auto_20181020_1247")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="note",
            field=models.ManyToManyField(
                blank=True, limit_choices_to={"active": True}, to="db.Note"
            ),
        )
    ]
