# Generated by Django 2.2 on 2019-05-01 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0007_estimate_note")]

    operations = [migrations.RemoveField(model_name="estimate", name="estimate_type")]
