# Generated by Django 2.2 on 2019-05-03 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0011_time_order")]

    operations = [migrations.DeleteModel(name="Newsletter")]
