# Generated by Django 2.1.8 on 2019-05-09 18:31

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("db", "0013_estimate_estimate_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="settingsapp", name="tags"),
        migrations.AddField(
            model_name="client",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
