# Generated by Django 2.1.9 on 2019-06-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0015_profile_job_title")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="job_title",
            field=models.CharField(blank=True, max_length=150, null=True),
        )
    ]
