# Generated by Django 2.1.9 on 2019-07-01 22:55

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0017_profile_twitter_username")]

    operations = [
        migrations.RemoveField(model_name="contract", name="client"),
        migrations.RemoveField(model_name="contract", name="project"),
        migrations.RemoveField(model_name="contract", name="statement_of_work"),
        migrations.RemoveField(model_name="contract", name="task"),
        migrations.DeleteModel(name="Elevation"),
        migrations.DeleteModel(name="File"),
        migrations.DeleteModel(name="Location"),
        migrations.DeleteModel(name="Log"),
        migrations.RemoveField(model_name="proposal", name="client"),
        migrations.RemoveField(model_name="proposal", name="project"),
        migrations.RemoveField(model_name="proposal", name="statement_of_work"),
        migrations.RemoveField(model_name="proposal", name="task"),
        migrations.DeleteModel(name="Service"),
        migrations.DeleteModel(name="SettingsApp"),
        migrations.RemoveField(model_name="settingscompany", name="note"),
        migrations.DeleteModel(name="Zipcode"),
        migrations.RemoveField(model_name="time", name="order"),
        migrations.AlterField(
            model_name="profile",
            name="dashboard_items",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("times", "Times"), ("totals", "Totals")],
                max_length=12,
                null=True,
                verbose_name="Dashboard Items",
            ),
        ),
        migrations.DeleteModel(name="Contract"),
        migrations.DeleteModel(name="Order"),
        migrations.DeleteModel(name="Proposal"),
        migrations.DeleteModel(name="SettingsCompany"),
    ]
