# Generated by Django 2.1.9 on 2019-07-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0019_siteconfiguration")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="company_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="company_name",
            field=models.CharField(default="Company Name", max_length=255),
        ),
    ]
