# Generated by Django 2.1.9 on 2019-07-02 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0021_project_user_hours")]

    operations = [migrations.RemoveField(model_name="project", name="user_hours")]
