# Generated by Django 2.1.10 on 2019-07-06 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0023_auto_20190705_2318")]

    operations = [
        migrations.RemoveField(model_name="note", name="contacts"),
        migrations.RemoveField(model_name="note", name="tags"),
        migrations.RemoveField(model_name="note", name="user"),
    ]
