# Generated by Django 2.1.10 on 2019-07-07 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0024_auto_20190706_1243")]

    operations = [
        migrations.RenameField(model_name="note", old_name="note", new_name="text")
    ]
