# Generated by Django 2.1.10 on 2019-07-07 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0025_auto_20190707_1929")]

    operations = [migrations.RemoveField(model_name="client", name="note")]
