# Generated by Django 3.0.4 on 2020-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0034_taskorder_name")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="notifications",
            field=models.BooleanField(default=False),
        )
    ]
