# Generated by Django 3.0.4 on 2020-04-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0036_account")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="number",
            field=models.CharField(blank=True, max_length=300, null=True),
        )
    ]
