# Generated by Django 3.0.4 on 2020-04-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0037_account_number")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="note",
            field=models.ManyToManyField(
                blank=True, limit_choices_to={"active": True}, to="db.Note"
            ),
        )
    ]
