# Generated by Django 3.0.4 on 2020-05-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0039_order")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="doc_type",
            field=models.CharField(blank=True, max_length=300, null=True),
        )
    ]
