# Generated by Django 3.0.4 on 2020-06-02 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0041_auto_20200602_2242")]

    operations = [migrations.DeleteModel(name="Order")]
