# Generated by Django 3.0.7 on 2020-06-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0042_delete_order")]

    operations = [
        migrations.AddField(
            model_name="time",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1.0,
                max_digits=12,
                null=True,
                verbose_name="Quantity",
            ),
        ),
        migrations.AddField(
            model_name="time",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1.0,
                max_digits=12,
                null=True,
                verbose_name="Unit",
            ),
        ),
        migrations.AddField(
            model_name="time",
            name="unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1.0,
                max_digits=12,
                null=True,
                verbose_name="Unit",
            ),
        ),
        migrations.AddField(
            model_name="time",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1.0,
                max_digits=12,
                null=True,
                verbose_name="Unit",
            ),
        ),
    ]
