# Generated by Django 3.0.7 on 2020-06-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0043_auto_20200612_1453")]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1.0,
                max_digits=12,
                null=True,
                verbose_name="Total Price",
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1.0,
                max_digits=12,
                null=True,
                verbose_name="Unit Price",
            ),
        ),
    ]
