# Generated by Django 3.0.7 on 2020-06-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0044_auto_20200612_1558")]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="unit",
            field=models.CharField(blank=True, max_length=2, null=True),
        )
    ]
