# Generated by Django 3.0.7 on 2020-07-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0046_auto_20200628_1328")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        )
    ]
