# Generated by Django 3.0.7 on 2020-07-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0047_profile_username")]

    operations = [
        migrations.RemoveField(model_name="profile", name="username"),
        migrations.AddField(
            model_name="profile",
            name="interest",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=1.0,
                max_digits=12,
                null=True,
                verbose_name="Interest",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="principal",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=1.0,
                max_digits=12,
                null=True,
                verbose_name="Principal",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="term",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=1.0,
                max_digits=12,
                null=True,
                verbose_name="Term",
            ),
        ),
    ]
