# Generated by Django 3.0.7 on 2020-07-28 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0052_note__note")]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        )
    ]
