# Generated by Django 3.0.7 on 2020-09-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0053_auto_20200728_1704")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="ein",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
