# Generated by Django 3.1.4 on 2021-01-03 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0054_invoice_ein")]

    operations = [
        migrations.RemoveField(model_name="profile", name="interest"),
        migrations.RemoveField(model_name="profile", name="principal"),
        migrations.RemoveField(model_name="profile", name="term"),
    ]
