# Generated by Django 3.1.4 on 2021-01-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0056_time_amount")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="gross",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="net",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
