# Generated by Django 3.1.4 on 2021-01-13 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0060_auto_20210113_2136")]

    operations = [
        migrations.RemoveField(model_name="time", name="cost_amount"),
        migrations.RemoveField(model_name="time", name="cost_rate"),
        migrations.RemoveField(model_name="time", name="currency"),
        migrations.RemoveField(model_name="time", name="department"),
        migrations.RemoveField(model_name="time", name="external_reference_url"),
        migrations.RemoveField(model_name="time", name="first_name"),
        migrations.RemoveField(model_name="time", name="last_name"),
        migrations.RemoveField(model_name="time", name="project_code"),
    ]
