# Generated by Django 3.1.4 on 2021-01-13 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0061_auto_20210113_2333")]

    operations = [
        migrations.RemoveField(model_name="time", name="billable"),
        migrations.RemoveField(model_name="time", name="employee"),
    ]
