# Generated by Django 3.1.4 on 2021-01-13 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0062_auto_20210113_2335")]

    operations = [
        migrations.RemoveField(model_name="time", name="estimate"),
        migrations.DeleteModel(name="Estimate"),
    ]
