# Generated by Django 3.1.4 on 2021-01-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0063_auto_20210113_2341")]

    operations = [
        migrations.AddField(
            model_name="time",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        )
    ]
