# Generated by Django 3.1.4 on 2021-01-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0065_time_net")]

    operations = [
        migrations.AddField(
            model_name="report",
            name="projects",
            field=models.ManyToManyField(blank=True, to="db.Project"),
        )
    ]
