# Generated by Django 3.1.4 on 2021-01-18 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0066_report_projects")]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.client",
            ),
        )
    ]
