# Generated by Django 3.1.4 on 2021-01-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0069_auto_20210118_1232")]

    operations = [
        migrations.AddField(
            model_name="report",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        )
    ]
