# Generated by Django 3.1.4 on 2021-01-19 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0071_remove_report_amount")]

    operations = [
        migrations.RenameField(model_name="report", old_name="gross", new_name="amount")
    ]
