# Generated by Django 3.1.4 on 2021-01-20 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0073_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="note",
            field=models.ManyToManyField(blank=True, to="db.Note"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="note",
            field=models.ManyToManyField(blank=True, to="db.Note"),
        ),
        migrations.AlterField(
            model_name="note",
            name="_note",
            field=models.ManyToManyField(blank=True, to="db.Note"),
        ),
        migrations.AlterField(
            model_name="project",
            name="team",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.company",
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.client",
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.project",
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.task",
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
