# Generated by Django 3.1.4 on 2021-01-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0074_auto_20210120_2254")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1.0,
                max_digits=12,
                null=True,
                verbose_name="Hours",
            ),
        )
    ]
