# Generated by Django 3.1.4 on 2021-01-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0076_report_hours")]

    operations = [
        migrations.AddField(
            model_name="company",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.client",
            ),
        )
    ]
