# Generated by Django 3.1.4 on 2021-01-21 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0077_company_client")]

    operations = [
        migrations.RemoveField(model_name="company", name="client"),
        migrations.AddField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.company",
            ),
        ),
    ]
