# Generated by Django 3.1.4 on 2021-01-21 23:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0078_auto_20210121_1634")]

    operations = [
        migrations.RemoveField(model_name="account", name="hidden"),
        migrations.RemoveField(model_name="account", name="tags"),
        migrations.RemoveField(model_name="client", name="hidden"),
        migrations.RemoveField(model_name="client", name="tags"),
        migrations.RemoveField(model_name="company", name="hidden"),
        migrations.RemoveField(model_name="company", name="tags"),
        migrations.RemoveField(model_name="contact", name="hidden"),
        migrations.RemoveField(model_name="contact", name="tags"),
        migrations.RemoveField(model_name="invoice", name="hidden"),
        migrations.RemoveField(model_name="invoice", name="tags"),
        migrations.RemoveField(model_name="note", name="hidden"),
        migrations.RemoveField(model_name="note", name="tags"),
        migrations.RemoveField(model_name="profile", name="hidden"),
        migrations.RemoveField(model_name="profile", name="tags"),
        migrations.RemoveField(model_name="project", name="hidden"),
        migrations.RemoveField(model_name="project", name="tags"),
        migrations.RemoveField(model_name="report", name="hidden"),
        migrations.RemoveField(model_name="report", name="tags"),
        migrations.RemoveField(model_name="service", name="hidden"),
        migrations.RemoveField(model_name="service", name="tags"),
        migrations.RemoveField(model_name="task", name="hidden"),
        migrations.RemoveField(model_name="task", name="tags"),
        migrations.RemoveField(model_name="testimonial", name="hidden"),
        migrations.RemoveField(model_name="testimonial", name="tags"),
        migrations.RemoveField(model_name="time", name="hidden"),
        migrations.RemoveField(model_name="time", name="tags"),
    ]
