# Generated by Django 3.1.4 on 2021-01-22 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0079_auto_20210121_2323")]

    operations = [migrations.RemoveField(model_name="task", name="billable")]
