# Generated by Django 3.1.4 on 2021-01-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0084_profile_note")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="lounge_password",
            field=models.CharField(blank=True, max_length=150, null=True),
        )
    ]
