# Generated by Django 3.1.4 on 2021-02-06 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0088_note_pin")]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="project",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.project",
            ),
        )
    ]
