# Generated by Django 3.1.6 on 2021-02-13 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0089_auto_20210206_2041")]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="client",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.client",
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="task",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.task",
            ),
        ),
    ]
