# Generated by Django 3.1.4 on 2021-02-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0090_auto_20210213_1835")]

    operations = [
        migrations.RenameField(
            model_name="client", old_name="published", new_name="publish"
        ),
        migrations.RenameField(
            model_name="company", old_name="published", new_name="publish"
        ),
        migrations.RenameField(
            model_name="profile", old_name="published", new_name="publish"
        ),
        migrations.RenameField(
            model_name="service", old_name="published", new_name="publish"
        ),
        migrations.AddField(
            model_name="account",
            name="publish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="publish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="publish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note", name="publish", field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name="project",
            name="publish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="publish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task", name="publish", field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name="testimonial",
            name="publish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="time", name="publish", field=models.BooleanField(default=False)
        ),
    ]
