# Generated by Django 3.1.4 on 2021-02-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0091_auto_20210214_1720")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscribe",
            field=models.BooleanField(default=False),
        )
    ]
