# Generated by Django 3.1.7 on 2021-04-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0092_profile_subscribe")]

    operations = [
        migrations.DeleteModel(name="Service"),
        migrations.DeleteModel(name="Testimonial"),
        migrations.RenameField(
            model_name="contact", old_name="subscribed", new_name="subscribe"
        ),
        migrations.RemoveField(model_name="profile", name="lounge_password"),
        migrations.AlterField(
            model_name="account",
            name="url",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="ein",
            field=models.IntegerField(blank=True, null=True, verbose_name="EIN"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="subscribe",
            field=models.BooleanField(default=False, verbose_name="Notifications"),
        ),
        migrations.AlterField(
            model_name="time",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"last_payment_date": None},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.invoice",
            ),
        ),
    ]
