# Generated by Django 3.1.7 on 2021-04-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0095_service")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="lounge_password",
            field=models.CharField(blank=True, max_length=150, null=True),
        )
    ]
