# Generated by Django 3.1.7 on 2021-04-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0096_profile_lounge_password")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="lounge_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        )
    ]
