# Generated by Django 3.1.7 on 2021-06-17 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0098_expense")]

    operations = [
        migrations.RemoveField(model_name="contact", name="subscribe"),
        migrations.RemoveField(model_name="profile", name="subscribe"),
    ]
