# Generated by Django 3.1.7 on 2021-06-17 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0099_auto_20210617_1302")]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="notifications", new_name="mail"
        )
    ]
