# Generated by Django 3.1.7 on 2021-07-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0101_profile_dark")]

    operations = [
        migrations.AddField(
            model_name="report",
            name="clients",
            field=models.ManyToManyField(blank=True, to="db.Client"),
        ),
        migrations.AddField(
            model_name="report",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="db.Contact"),
        ),
    ]
