# Generated by Django 3.2.11 on 2022-01-23 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("db", "0102_auto_20210717_1017")]

    operations = [migrations.DeleteModel(name="SiteConfiguration")]
