# Generated by Django 3.2.11 on 2022-01-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0103_delete_siteconfiguration")]

    operations = [
        migrations.RemoveField(model_name="note", name="doc_type"),
        migrations.RemoveField(model_name="note", name="due_date"),
        migrations.AddField(
            model_name="note", name="html", field=models.BooleanField(default=False)
        ),
    ]
