# Generated by Django 3.2.11 on 2022-01-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0104_auto_20220130_1633")]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="html",
            field=models.BooleanField(default=False, verbose_name="HTML"),
        )
    ]
