# Generated by Django 3.2.11 on 2022-02-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0105_alter_note_html")]

    operations = [
        migrations.AddField(
            model_name="report",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.Note"),
        )
    ]
