# Generated by Django 4.0.5 on 2022-08-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0110_project_po_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="po_number",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="PO Number"
            ),
        ),
    ]
