# Generated by Django 4.0.5 on 2022-08-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0111_alter_project_po_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="ein",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
