# Generated by Django 4.2.1 on 2023-05-08 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("db", "0112_company_ein"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RemoveField(
            model_name="account",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="account",
            name="note",
        ),
        migrations.RemoveField(
            model_name="account",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="client",
            name="ignore",
        ),
        # migrations.RemoveField(
        #     model_name="client",
        #     name="publish",
        # ),
        migrations.RemoveField(
            model_name="company",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="company",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="note",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="note",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="note",
            name="pin",
        ),
        migrations.RemoveField(
            model_name="note",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="note",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="project",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="project",
            name="note",
        ),
        migrations.RemoveField(
            model_name="project",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="report",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="report",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="service",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="service",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="task",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="task",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="time",
            name="ignore",
        ),
        migrations.RemoveField(
            model_name="time",
            name="publish",
        ),
        migrations.AddField(
            model_name="account",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="account",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="client",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="company",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="contact",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="expense",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="profile",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="companies",
            field=models.ManyToManyField(to="db.company"),
        ),
        migrations.AddField(
            model_name="project",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="project",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="service",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="task",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="time",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="time",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="time",
            name="notes",
            field=models.ManyToManyField(blank=True, to="db.note"),
        ),
        migrations.AddField(
            model_name="time",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="time",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="ein",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="EIN"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.company",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dark",
            field=models.BooleanField(default=True, verbose_name="Dark Mode"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.task",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
