# Generated by Django 4.2.1 on 2023-05-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0114_alter_client_company_alter_contact_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.task",
            ),
        ),
    ]
