# Generated by Django 4.2.1 on 2023-05-18 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0119_alter_client_created_alter_client_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.client",
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.project",
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.task",
            ),
        ),
    ]
