# Generated by Django 4.2.1 on 2023-06-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_report_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="times",
                to="db.invoice",
            ),
        ),
    ]
