# Generated by Django 4.2.1 on 2023-06-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0123_alter_time_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="tasks",
            field=models.ManyToManyField(blank=True, to="db.task"),
        ),
    ]
