# Generated by Django 4.2.1 on 2023-06-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0124_report_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="reports",
            field=models.ManyToManyField(blank=True, to="db.report"),
        ),
    ]
