# Generated by Django 4.2.1 on 2023-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0126_project_draggable_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="github_access_token",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
