# Generated by Django 4.2.1 on 2023-06-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0128_client_github_project_github"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="github",
        ),
        migrations.RemoveField(
            model_name="project",
            name="github",
        ),
        migrations.AddField(
            model_name="client",
            name="github_organization",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="GitHub Organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="github_project",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="GitHub Project"
            ),
        ),
    ]
