# Generated by Django 4.2.3 on 2023-08-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0129_remove_client_github_remove_project_github_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="github_access_token",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="github_repository",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="GitHub Repository"
            ),
        ),
    ]
