# Generated by Django 4.2.4 on 2023-08-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0130_client_github_access_token_project_github_repository"),
    ]

    operations = [
        migrations.AddField(
            model_name="time",
            name="template_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("developer_communication", "Developer Communication"),
                    ("issue_management", "Issue Management"),
                    ("infrastructure_management", "Infrastructure Management"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
