# Generated by Django 4.2.4 on 2023-09-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0131_time_template_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="template_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("developer_communications", "Developer Communications"),
                    ("issue_management", "Issue Management"),
                    ("infrastructure_management", "Infrastructure Management"),
                    ("code_management", "Code Management"),
                    ("operations_support", "Operations Support"),
                    ("misc_tasks", "Miscellaneous Tasks"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
