# Generated by Django 5.0 on 2024-01-08 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0137_servicespage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactpage",
            name="intro",
        ),
    ]
