# Generated by Django 5.0 on 2024-01-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0139_careerspage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="number",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="url",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="URL"
            ),
        ),
    ]
