# Generated by Django 5.0.1 on 2024-01-14 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0143_profile_user_theme_preference"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lead",
        ),
    ]
