# Generated by Django 5.0.1 on 2024-01-14 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0144_delete_lead"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Expense",
        ),
    ]
