# Generated by Django 5.0.1 on 2024-01-20 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0147_note_contacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="ContactFormField",
        ),
        migrations.DeleteModel(
            name="ContactPage",
        ),
    ]
