# Generated by Django 5.0.2 on 2024-02-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0149_remove_time_template_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="github_access_token",
        ),
        migrations.RemoveField(
            model_name="client",
            name="github_organization",
        ),
        migrations.AddField(
            model_name="client",
            name="link",
            field=models.BooleanField(default=False),
        ),
    ]
