# Generated by Django 5.1 on 2024-10-05 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0153_taskorder_alter_timeentry_invoice_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="taskorder",
            table="taskorder",
        ),
    ]
