# Generated by Django 5.1.2 on 2024-12-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0157_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, default="aclark@aclark.net", max_length=254, null=True
            ),
        ),
    ]
