# Generated by Django 6.0 on 2025-12-30 03:28

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_path",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="redirect from"
                    ),
                ),
                (
                    "is_permanent",
                    models.BooleanField(
                        default=True,
                        help_text="Recommended. Permanent redirects ensure search engines forget the old page (the 'Redirect from') and index the new page instead.",
                        verbose_name="permanent",
                    ),
                ),
                (
                    "redirect_page_route_path",
                    models.CharField(
                        blank=True,
                        help_text="Optionally specify a route on the target page to redirect to. Leave blank to redirect to the default page route.",
                        max_length=255,
                        verbose_name="target page route",
                    ),
                ),
                (
                    "redirect_link",
                    models.URLField(
                        blank=True, max_length=255, verbose_name="redirect to any URL"
                    ),
                ),
                (
                    "automatically_created",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="automatically created",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created at"
                    ),
                ),
                (
                    "redirect_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.page",
                        verbose_name="redirect to a page",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redirects",
                        to="wagtailcore.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "redirect",
                "verbose_name_plural": "redirects",
                "unique_together": {("old_path", "site")},
            },
        ),
    ]
