version: 0.2

eb_codebuild_settings:
  CodeBuildServiceRole: "CodeBuildServiceRole"
  ComputeType: "BUILD_GENERAL1_SMALL"
  Image: "aws/codebuild/standard:5.0"
  Timeout: 5

phases:
  pre_build:
    commands:
      - n 21
      - "echo Install Phase: `date`"
      - npm install

  build:
    commands:
      - n 21
      - "echo Build Phase: `date`"
      - npm run build

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - '**/node_modules'
