# Generated by Django 6.0 on 2025-12-28 01:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0002_admin_userprofile_editingsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "marketing_blocks",
                    wagtail.fields.StreamField(
                        [("marketing_block", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter the block title",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Enter the block content",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.blocks.ListBlock",
                                (2,),
                                {
                                    "help_text": "Select one or two images for column display. Select three or more images for carousel display."
                                },
                            ),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Select one image for background display.",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "vh-100 app-ribbon",
                                    "form_classname": "full title",
                                    "help_text": "Enter a CSS class for styling the marketing block",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "img-thumbnail p-5",
                                    "form_classname": "full title",
                                    "help_text": "Enter a CSS class for styling the column display image(s)",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "d-flex flex-row",
                                    "form_classname": "full title",
                                    "help_text": "Enter a CSS class for styling the layout.",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("content", 1),
                                        ("images", 3),
                                        ("image", 4),
                                        ("block_class", 5),
                                        ("image_class", 6),
                                        ("layout_class", 7),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
