# Generated by Django 6.1.1 on 2026-10-03 19:53

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nowentry",
            name="id",
            field=django_mongodb_backend.fields.ObjectIdAutoField(
                primary_key=True, serialize=False
            ),
        ),
    ]
