# Generated by Django 6.0.4 on 2026-05-12 00:00

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="id",
            field=django_mongodb_backend.fields.ObjectIdAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
