# Generated by Django 6.1 on 2026-08-31 14:29

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('wagtailcore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A human-readable label to identify this token.', max_length=255, verbose_name='name')),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
            ],
            options={
                'verbose_name': 'API token',
                'verbose_name_plural': 'API tokens',
            },
        ),
        migrations.AddIndex(
            model_name='modellogentry',
            index=models.Index(fields=['uuid', 'action', '-timestamp'], name='wagtailcore_uuid_d6363b_idx'),
        ),
        migrations.AddIndex(
            model_name='pagelogentry',
            index=models.Index(fields=['uuid', 'action', '-timestamp'], name='wagtailcore_uuid_06a44d_idx'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
