"""Tests for Time description field display in related template."""

from django.contrib.auth import get_user_model
from django.test import TestCase, RequestFactory
from django.template import Context, Template

from db.models import Company, Client, Project, Invoice, Time
from db.views.invoice import InvoiceDetailView

User = get_user_model()


class TimeDescriptionInRelatedTemplateTest(TestCase):
    """Test that Time description field appears in related.html template."""

    def setUp(self):
        """Set up test data."""
        self.factory = RequestFactory()
        self.user = User.objects.create_superuser(
            username="admin",
            email="admin@example.com",
            password="admin123",
        )
        
        # Create full hierarchy
        self.company = Company.objects.create(name="Test Company")
        self.client = Client.objects.create(name="Test Client", company=self.company)
        self.project = Project.objects.create(name="Test Project", client=self.client)
        self.invoice = Invoice.objects.create(name="Test Invoice", project=self.project)
        
        # Create time entry with description
        self.time_with_desc = Time.objects.create(
            user=self.user,
            project=self.project,
            invoice=self.invoice,
            hours=8.0,
            description="Implemented feature X",
        )
        
        # Create time entry without description
        self.time_without_desc = Time.objects.create(
            user=self.user,
            project=self.project,
            invoice=self.invoice,
            hours=4.0,
            description="",
        )

    def test_invoice_view_includes_time_with_description(self):
        """Test that Invoice detail view field_values includes time description."""
        request = self.factory.get(f'/invoice/{self.invoice.pk}/')
        request.user = self.user
        
        view = InvoiceDetailView()
        view.request = request
        view.object = self.invoice
        view.kwargs = {'pk': self.invoice.pk}
        
        context = view.get_context_data()
        
        # Check that has_related is True
        self.assertTrue(context.get('has_related', False))
        
        # Get field_values_page
        field_values_page = context.get('field_values_page', [])
        self.assertGreater(len(field_values_page), 0)
        
        # Check that description field is in the field values for time entries
        time_field_values = None
        for item_fields in field_values_page:
            # Find the time entry with description
            for field_name, field_value in item_fields:
                if field_name == "id" and field_value == self.time_with_desc.id:
                    time_field_values = item_fields
                    break
            if time_field_values:
                break
        
        self.assertIsNotNone(time_field_values, "Time entry not found in field_values_page")
        
        # Check that description field is present
        field_dict = dict(time_field_values)
        self.assertIn("description", field_dict)
        self.assertEqual(field_dict["description"], "Implemented feature X")

    def test_related_template_renders_description_in_card_text(self):
        """Test that related.html template renders description in card text with label."""
        # Simulate the template rendering with time entry field values
        # Time entries use related_title_fields = ["name", "title", "subject"]
        # so description should appear in card text, not title
        template_string = """
        {% load text_filters %}
        {% for field_values in field_values_page %}
          {% if field_values %}
            {% with model_name=field_values.0.1 object_id=field_values.1.1 %}
              <h5 class="card-title">
                <span class="badge">{{ model_name|title }}</span>
                {% for field_name, field_value in field_values %}
                  {% if field_name == "name" or field_name == "title" or field_name == "subject" %}
                    {{ field_value|default:"" }}
                  {% endif %}
                {% endfor %}
              </h5>
              <div class="card-text">
                {% for field_name, field_value in field_values %}
                  {% if field_name not in related_excluded_fields and field_name not in related_title_fields and field_value %}
                    <strong>{{ field_name|title }}:</strong> {{ field_value|truncatewords:10 }}<br>
                  {% endif %}
                {% endfor %}
              </div>
            {% endwith %}
          {% endif %}
        {% endfor %}
        """
        
        # Create mock field values like those generated by get_field_values
        field_values_page = [
            [
                ("type", "time"),
                ("id", self.time_with_desc.id),
                ("date", self.time_with_desc.date),
                ("hours", self.time_with_desc.hours),
                ("description", "Implemented feature X"),
                ("user", self.user),
            ]
        ]
        
        # Time view uses these configurations
        related_title_fields = ["name", "title", "subject"]  # description NOT in title
        related_excluded_fields = ["type", "id", "item"]
        
        template = Template(template_string)
        context = Context({
            "field_values_page": field_values_page,
            "related_title_fields": related_title_fields,
            "related_excluded_fields": related_excluded_fields,
        })
        rendered = template.render(context)
        
        # Check that description appears in the card text (not title)
        self.assertIn("Implemented feature X", rendered)
        self.assertIn('<span class="badge">Time</span>', rendered)
        # Check that description has a label in card-text
        self.assertIn("Description:", rendered)

    def test_time_entries_with_and_without_description(self):
        """Test that both time entries appear in invoice view."""
        request = self.factory.get(f'/invoice/{self.invoice.pk}/')
        request.user = self.user
        
        view = InvoiceDetailView()
        view.request = request
        view.object = self.invoice
        view.kwargs = {'pk': self.invoice.pk}
        
        context = view.get_context_data()
        field_values_page = context.get('field_values_page', [])
        
        # Count time entries in field_values_page
        time_count = 0
        for item_fields in field_values_page:
            field_dict = dict(item_fields)
            if field_dict.get("type") == "time":
                time_count += 1
        
        # Both time entries should be present
        self.assertEqual(time_count, 2)
